name: CI - Testes da API de Sensores IoT

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout do código
        uses: actions/checkout@v3

      - name: 🟢 Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'

      - name: 📦 Instalar dependências
        run: npm install

      - name: 🧪 Executar testes
        run: npm test
